### PR TITLE
Replace str.format() with f-strings in nmcli.py 

### PR DESCRIPTION
**Pull request by MosheSheena**
Due to the drop of Python3.5 in this [PR](https://github.com/rhevm-qe-automation/python-rrmngmnt/pull/133)
I replaced, where appropriate, the format() to f-strings.

### CODE REVIEW

**Comment by MosheSheena** [comment]
Once [PR](https://github.com/rhevm-qe-automation/python-rrmngmnt/pull/133) is merged - this PR can pass CI.
Currently, it is expected to fail since Python3.5 does not support f-strings.

**Review by lukas-bednar — COMMENTED** [review]
I don't have a problem with it. However commit message claims "Replace str.format() with f-strings" but this PR changes only single file. So maybe something like "Replace str.format() with f-strings in nmcli.py" would be more appropriate.

**Comment by MosheSheena** [comment]
@lukas-bednar hi do you have any idea on how to increase coverage? I'm not sure why codecov treats this as a decrease...

**Comment by lukas-bednar** [comment]
> @lukas-bednar hi do you have any idea on how to increase coverage? I'm not sure why codecov treats this as a decrease...

This is not really problem, based on changes you have made, you removed some lines, which leads to decrease of coverage - but in this case it is all right.

**Comment by MosheSheena** [comment]
> > @lukas-bednar hi do you have any idea on how to increase coverage? I'm not sure why codecov treats this as a decrease...
> 
> This is not really problem, based on changes you have made, you removed some lines, which leads to decrease of coverage - but in this case it is all right.

So can we please merge?

**Comment by lukas-bednar** [comment]
Sure, could you please rebase your patch on current master ?

**Comment by MosheSheena** [comment]
Hi,  @lukas-bednar I rebased. do you think this PR can be merged?

**Comment by lukas-bednar** [comment]
@MosheSheena It seems that your rebase is not taking an affect. This PR contains commits which has been already merged.

Please try to fix that.

**Comment by MosheSheena** [comment]
> @MosheSheena It seems that your rebase is not taking an affect. This PR contains commits which has been already merged.
> 
> Please try to fix that.

I'm not sure what else I can do.
This branch is already rebased over #133 and #135 which were my only changes.
This PR and #136 are the only ones that are open.

**Comment by MosheSheena** [comment]
@myakove can you please review?

**Comment by MosheSheena** [comment]
@lukas-bednar Can we please merge?

**Pull request merged**
